In [1]:
# lets start practice of numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(4,3)

In [8]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
# 2d array
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [23]:
arr.reshape(12,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.arange(1,5)

array([1, 2, 3, 4])

In [33]:
np.random.random((3,4))

array([[0.59499832, 0.48225406, 0.43075743, 0.30132134],
       [0.43336722, 0.7569305 , 0.3310046 , 0.71717915],
       [0.24296862, 0.82956542, 0.61709605, 0.00277301]])

In [36]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [37]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.linspace((1,110),(10,10),100)

array([[  1.        , 110.        ],
       [  1.09090909, 108.98989899],
       [  1.18181818, 107.97979798],
       [  1.27272727, 106.96969697],
       [  1.36363636, 105.95959596],
       [  1.45454545, 104.94949495],
       [  1.54545455, 103.93939394],
       [  1.63636364, 102.92929293],
       [  1.72727273, 101.91919192],
       [  1.81818182, 100.90909091],
       [  1.90909091,  99.8989899 ],
       [  2.        ,  98.88888889],
       [  2.09090909,  97.87878788],
       [  2.18181818,  96.86868687],
       [  2.27272727,  95.85858586],
       [  2.36363636,  94.84848485],
       [  2.45454545,  93.83838384],
       [  2.54545455,  92.82828283],
       [  2.63636364,  91.81818182],
       [  2.72727273,  90.80808081],
       [  2.81818182,  89.7979798 ],
       [  2.90909091,  88.78787879],
       [  3.        ,  87.77777778],
       [  3.09090909,  86.76767677],
       [  3.18181818,  85.75757576],
       [  3.27272727,  84.74747475],
       [  3.36363636,  83.73737374],
 